27-authentication/snack-tracking/config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  get '/whatever', to: "snacks#home", as: "home"
  get '/fun', to: "snacks#my_super_fun_page"
  # get '/snacks', to: "snack#index", as: "snacks"
  # get '/snacks/:id', to: "snack#show", as: "snack"
  resources :snacks
  resources :retailers, only: [:index, :show, :new, :create]
  resources :users, only: [:new, :create]

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#logout"
end

27-authentication/snack-tracking/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

27-authentication/snack-tracking/app/models/retailer.rb
class Retailer < ApplicationRecord
    has_many :snacks
    accepts_nested_attributes_for :snacks

    def just_say_hi
        "Hi"
    end
end

27-authentication/snack-tracking/app/models/snack.rb
class Snack < ApplicationRecord
    belongs_to :retailer
end

27-authentication/snack-tracking/app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :username, presence: true, uniqueness: {case_sensitive: false}

end

27-authentication/snack-tracking/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


    def get_current_user
        User.find_by(username: session[:username])
    end

    def logged_in?
        !!get_current_user
    end

    def authorized
        redirect_to login_path unless logged_in?
    end

end

27-authentication/snack-tracking/app/controllers/retailers_controller.rb
class RetailersController < ApplicationController

  before_action :authorized
  
  def index
     @retailers = Retailer.all
  end

  def show
    @retailer = Retailer.find(params[:id])
  end

  def new
    @retailer = Retailer.new
    @retailer.snacks.build
  end

  def create
    retailer = Retailer.create(retailer_strong_params)
    redirect_to retailer_path(retailer)
  end

  private

  def retailer_strong_params
    params.require(:retailer).permit(:name, :year_established,
        snacks_attributes: [:name, :calories, :deliciousness])
  end
end

27-authentication/snack-tracking/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
        if session["username"]
            redirect_to snacks_path
        else
            render :new
        end

    end

    def create
        username = params[:username]
        user = User.find_by(username: username)
        if user && user.authenticate(params[:password])
            session["username"] = user.username
            redirect_to snacks_path
        else
            flash["error"] = "No user found with that name and password"
            redirect_to login_path
        end
    end

    def logout
        session.clear
        redirect_to login_path
    end


end

27-authentication/snack-tracking/app/controllers/snacks_controller.rb
class SnacksController < ApplicationController

  before_action :find_snack, only: [:show, :edit, :update, :destroy]
  before_action :authorized, except: [:home]

  def home
  end

  def index
    @snacks = Snack.all 
    render :index
  end

  def my_super_fun_page
  end

  def show
    cookies["my_favorite"] = "chocolate chip"
    cookies["last_visited"] = @snack.name
    session["secret_favorite"] = "oatmeal raisin"
  end

  def new
    @snack = Snack.new
  end

  def create
    snack = Snack.create(snack_strong_params)
    redirect_to snack_path(snack)
  end

  def edit
  end

  def update
    @snack.update(snack_strong_params)
    redirect_to (snack_path(@snack))
  end

  def destroy
    @snack.delete
    redirect_to snacks_path
  end

  def find_snack
    @snack = Snack.find(params[:id])
  end

  private

  def snack_strong_params
    params.require(:snack).permit(:name, :calories, :deliciousness, :retailer_id)

  end

end

27-authentication/snack-tracking/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create 
    @user = User.new(user_params)
    if @user.valid?

        @user.save
        session[:username] = @user.username
        redirect_to snacks_path
    else
        render :new
    end

  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

27-authentication/snack-tracking/app/helpers/application_helper.rb
module ApplicationHelper
end

27-authentication/snack-tracking/app/helpers/retailers_helper.rb
module RetailersHelper
end

27-authentication/snack-tracking/app/helpers/sessions_helper.rb
module SessionsHelper
end

27-authentication/snack-tracking/app/helpers/snack_helper.rb
module SnackHelper
end

27-authentication/snack-tracking/app/helpers/users_helper.rb
module UsersHelper
end

27-authentication/snack-tracking/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SnackTracking</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if session["username"] %>
      <span>Welcome <%= session["username"] %></span>
      <span><%= link_to "Logout", logout_path, method: "delete" %></span>
    <% else %>
      <%= link_to "Log in", login_path %>
    <% end %>
    <%= yield %>
  </body>
</html>

27-authentication/snack-tracking/app/views/retailers/index.html.erb
<h1>Retailers#index</h1>
<p>Find me in app/views/retailers/index.html.erb</p>


<ul>
    <% @retailers.each do |ret| %>
        <li><%= link_to ret.name, retailer_path(@ret.id) %></li>
    <% end %>
</ul>

27-authentication/snack-tracking/app/views/retailers/new.html.erb
<h1>Create a New Retailer</h1>

<%= form_for @retailer do |ret| %>
    <%= ret.label :name %>
    <%= ret.text_field :name %>
    <%= ret.label :year_established %>
    <%= ret.number_field :year_established, {min: 1700} %>


    <h2>Snacks by this retailer</h2>
        <% 3.times do %>
            <div>
            <%= ret.fields_for :snacks do |snack| %>
                <%= snack.label :name %>
                <%= snack.text_field :name %>
                <%= snack.label :calories %>
                <%= snack.number_field :calories, step: 50 %>
                <%= snack.label :deliciousness %>
                <%= snack.number_field :deliciousness %>

            <% end %>

            </div>
        <% end %>
    <%= ret.submit %>
<% end %>

27-authentication/snack-tracking/app/views/retailers/show.html.erb
<h1>Detail page for <%= @retailer.name %></h1>

<h2>Established in <%= @retailer.year_established %></h2>

<ul>
<% @retailer.snacks.each do |snack| %>
    <li><%= link_to snack.name, snack_path(snack) %></li>
<% end %>
</ul>

27-authentication/snack-tracking/app/views/snacks/_snack_form.html.erb
<%= form_for @snack do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :calories %>
    <%= f.number_field :calories %>
    <%= f.label :deliciousness %>
    <%= f.select :deliciousness, (1..10) %>
    <%= f.label :retailer %>
    <%= f.collection_select(:retailer_id, Retailer.all, :id, :name, prompt: true) %>

    <%= f.submit submit_text %>
<% end %>

27-authentication/snack-tracking/app/views/snacks/edit.html.erb
<h1>Edit this snack</h1>

<%= render partial: "snack_form", locals: {submit_text: "Edit this snack" } %>

27-authentication/snack-tracking/app/views/snacks/home.html.erb
<h1>Welcome to our super Snack app!</h1>


<%= link_to "Enter our app", snacks_path %>

27-authentication/snack-tracking/app/views/snacks/index.html.erb
<h1>Snack#index</h1>
<h2>This is the snack page for <%= session["username"] %></h2>

<p>Find me in app/views/snack/index.html.erb</p>

<h2>My favorite cookie is <%= cookies["my_favorite"] %></h2>
<h4>My secret favorite cookie is <%= session["secret_favorite"] %></h4>
<h3>The last snack I visited was <%= cookies["last_visited"] %></h3>

<ul>
    <% @snacks.each do |snack| %>
        <li><%= link_to snack.name, snack_path(snack) %></li>
    <% end %>
</ul>

<%= link_to "Home", home_path %>

27-authentication/snack-tracking/app/views/snacks/my_super_fun_page.html.erb
<% 100.times do %>
    <h1>FUN FUN FUN</h1>
<% end %>

27-authentication/snack-tracking/app/views/snacks/new.html.erb
<h2>Create a new snack</h2>


<%= render partial: "snack_form", locals: {submit_text: "Create a new snack"} %>

27-authentication/snack-tracking/app/views/snacks/show.html.erb
<h1>Detail page</h1>

<h2><%= @snack.name %></h2>

<h3>Calories: <%= @snack.calories %></h3>
<h3>Deliciousness: <%= @snack.deliciousness %></h3>


<%= link_to "Edit this snack", edit_snack_path(@snack) %>
<%= link_to "Delete this snack", snack_path(@snack), :method => :delete, data: {:confirm => "Do you really want to delete this delicious snack?"} %>
<%= link_to "Index Page", snacks_path %>

27-authentication/snack-tracking/app/views/users/new.html.erb
<h1>Create a new user or <%= link_to "login", login_path %></h1>

<% if @user.errors %>
    <% @user.errors.full_messages.each do |message| %>
        <%= message %>
    <% end %>
<% end %>

<%= form_for @user do |f| %>
    <%= f.label :username %>
    <%= f.text_field :username %>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <%= f.submit %>
<% end %>